//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ride_SharingApp.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Driver
    {
        public int DriverId { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string DriverName { get; set; }

        [Required]
       // [StringLength(13, ErrorMessage = "Must be {13} characters long.", MinimumLength = 13)]
        [Display(Name = "CNIC")]
        public string DriverCNIC { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string DriverEmail { get; set; }

        [Required]
        [Display(Name = "Phone #")]
        public string DriverPhone { get; set; }

        [Required]
        [Display(Name = "Ratings")]
        public Nullable<int> DriverAverageRating { get; set; }
    }
}
