//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ride_SharingApp.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string UserEmail { get; set; }

        [Required]
        //[StringLength(13, ErrorMessage = "Must be {13} characters long.",MinimumLength = 13)]
        [Display(Name = "CNIC")]
        public string UserCNIC { get; set; }

        [Required]
        [Display(Name = "Phone #")]
        public string UserPhone { get; set; }
       
    }
}
