//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ride_SharingApp.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        public int VehicleId { get; set; }

        [Required]
       // [StringLength (6, ErrorMessage = "Must be {6} characters long.",MinimumLength = 6)]
        [Display(Name = "Registration Number")]
        public string VehicleRegistrationNumber { get; set; }

        [Required]
        [Display(Name = "Owner Name")]
        public string VehicleOwnerName { get; set; }

        [Required]
        [Display(Name = "Model Year")]
        public string VehicleModel { get; set; }
    }
}
